import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml",
]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { shape = "Block", blinking = "Always" }
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
size = 21.0
normal = { family = "monofur for Powerline", style = "Regular" }
italic = { family = "monofur for Powerline", style = "  italic" }
bold = { family = "monofur for Powerline", style = "  bold" }

[keyboard]
bindings = [
  { action = "Paste", key = "V", mods = "Command" },
  { action = "Copy", key = "C", mods = "Command" },
  { action = "Paste", key = "Paste" },
  { action = "Copy", key = "Copy" },
  { action = "Quit", key = "Q", mods = "Command" },
  { action = "Quit", key = "W", mods = "Command" },
  { action = "ScrollHalfPageUp", key = "U", mods = "Control" },
  { action = "ScrollHalfPageDown", key = "D", mods = "Control" },
  { action = "ScrollHalfPageDown", key = "D", mods = "Control" },
  { action = "SelectNextTab", key = "Tab", mods = "Control" },
  { action = "SelectPreviousTab", key = "Tab", mods = "Control|Shift" },
]

[scrolling]
history = 10000
multiplier = 3

[window]
opacity = 0.8
blur = true
decorations = "Full"
padding = { x = 20, y = 20 }
